function model = ge_pd_interconnect_model(cfg, responsivity)
scriptDir = fileparts(mfilename('fullpath'));
dataDir   = scriptDir;
if ~exist(dataDir, 'dir'), mkdir(dataDir); end

f   = logspace(8, 11.4, 1600);
w   = 2 * pi * f;
ctot  = cfg.Cj + cfg.Cp;
zcap  = 1 ./ (1i * w * ctot);
zload = 1 ./ (1 / cfg.R_load + 1 ./ zcap);
divider = abs(zload ./ (cfg.Rs + 1i * w * cfg.Lp + zload));
zt    = responsivity * abs(zload) .* divider ./ sqrt(1 + (f / cfg.f3dB).^2);
f_rc  = 1 / (2 * pi * (cfg.Rs + cfg.R_load) * ctot);
f_pkg = 1 / (2 * pi * sqrt(cfg.Lp * ctot));

model = struct( ...
    'f_Hz',     f(:), ...
    'f_GHz',    f(:) / 1e9, ...
    'zt_VW',    zt(:), ...
    'norm_dB',  20 * log10(zt(:) / max(zt)), ...
    'f_rc',     f_rc, ...
    'f_pkg',    f_pkg, ...
    'resp_AW',  responsivity ./ sqrt(1 + (f(:) / cfg.f3dB).^2));

bias_pts       = [-1.0, -1.5];
bandwidth_data = struct('voltage', bias_pts, 'bandwidth', [cfg.f3dB, cfg.f3dB]);
Idark_data     = struct('voltage', bias_pts, 'current',   [cfg.Id,   cfg.Id]);

lambda_min = 1260e-9;  lambda_max = 1360e-9;
f_cml = [3e8/lambda_max, 3e8/lambda_min];  % ascending frequency
R_cml = [responsivity, responsivity];       % flat across O-band
resp_data = struct('frequency', f_cml(:), 'responsivity', R_cml(:));

elec_eq_ckt_data = struct('Rj', cfg.Rs, 'Cj_data', cfg.Cj, 'Rp', cfg.R_load, 'Cp', cfg.Cp);

notes = { ...
    struct('property', 'source',          'value', 'Ge-on-Si O-band U-shaped VPD -- INTERCONNECT compact model.'), ...
    struct('property', 'design_target',   'value', '400G DR4 IEEE 802.3, PAM-4, 4x100G lanes.'), ...
    struct('property', 'bias_note',       'value', 'Bias-dependent entries duplicated from -1 V operating point.') ...
};
general    = struct('description', 'Ge-on-Si O-band U-shaped PD compact model for Lumerical INTERCONNECT.', ...
                    'prefix', 'PD', 'notes', {notes});
ports      = struct( ...
    'opt_1',  struct('name','opt_1',  'dir','Bidirectional','pos','Left',   'order',1), ...
    'ele_an', struct('name','ele_an', 'dir','Bidirectional','pos','Right',  'order',2), ...
    'ele_cat',struct('name','ele_cat','dir','Bidirectional','pos','Bottom', 'order',3));
model_data = struct( ...
    'photonic_model',         'photodetector_simple', ...
    'bandwidth_data',         bandwidth_data, ...
    'Idark_data',             Idark_data, ...
    'resp_data',              resp_data, ...
    'enable_shot_noise',      cfg.enable_shot_noise, ...
    'DC_operation_only',      false, ...
    'enable_power_saturation',true, ...
    'saturation_power_data',  cfg.Psat, ...
    'elec_eq_ckt_data',       elec_eq_ckt_data);

save(fullfile(dataDir, 'ge_pd_interconnect_model_data.mat'), 'general', 'ports', 'model_data');
writematrix([model.f_Hz, model.resp_AW], fullfile(dataDir, 'ge_pd_interconnect_resp.csv'));
writematrix([bandwidth_data.voltage(:), bandwidth_data.bandwidth(:)], ...
    fullfile(dataDir, 'ge_pd_interconnect_bandwidth.csv'));
writematrix([Idark_data.voltage(:), Idark_data.current(:)], ...
    fullfile(dataDir, 'ge_pd_interconnect_dark_current.csv'));

param_tbl = table( ...
    {'responsivity_A_W'; 'dark_current_A'; 'bandwidth_Hz'; 'Rs_Ohm'; 'Cj_F'; 'Cp_F'; 'Rload_Ohm'; 'Lp_H'; 'Psat_W'}, ...
    {responsivity; cfg.Id; cfg.f3dB; cfg.Rs; cfg.Cj; cfg.Cp; cfg.R_load; cfg.Lp; cfg.Psat}, ...
    'VariableNames', {'parameter', 'value'});
writetable(param_tbl, fullfile(dataDir, 'ge_pd_interconnect_parameters.csv'));

figDir = fullfile(fileparts(scriptDir), '..', 'thesis', 'figures');
if ~exist(figDir, 'dir'), mkdir(figDir); end

fig = figure('Color', 'w', 'Position', [150, 150, 1600, 1000], 'Name', 'INTERCONNECT Compact Model');
yyaxis left;
semilogx(model.f_GHz, model.zt_VW, 'k-', 'LineWidth', 2);
ylabel('Optical-to-electrical gain |Z_t| (V/W)', 'FontSize', 12, 'FontWeight', 'bold');
yyaxis right;
semilogx(model.f_GHz, model.norm_dB, 'k--', 'LineWidth', 2);
ylabel('Normalised response (dB)', 'FontSize', 12, 'FontWeight', 'bold');
xline(model.f_rc / 1e9,  'k:',  sprintf('f_{RC}=%.0f GHz',  f_rc/1e9),  'LineWidth', 1.5);
xline(model.f_pkg / 1e9, 'k-.', sprintf('f_{pkg}=%.0f GHz', f_pkg/1e9), 'LineWidth', 1.5);
xlabel('Frequency (GHz)', 'FontSize', 12, 'FontWeight', 'bold');
title('Ge-on-Si O-band VPD -- INTERCONNECT Compact Model', 'FontSize', 13, 'FontWeight', 'bold');
legend({'|Z_t|', 'Normalised EO response', 'f_{RC}', 'f_{pkg}'}, 'Location', 'southwest');
grid on;
set(gca, 'FontSize', 11, 'FontName', 'Times New Roman', 'LineWidth', 1.5, ...
    'GridAlpha', 0.15, 'TickDir', 'out', 'XMinorGrid', 'on', 'YMinorGrid', 'on');
save_fig(fig, figDir, 'system_interconnect_compact_model', 300);
fprintf('INTERCONNECT model data saved in %s\n', dataDir);
end

function save_fig(fig, outDir, baseName, dpi)
if ~exist(outDir, 'dir'), mkdir(outDir); end
set(fig, 'Color', 'w', 'InvertHardcopy', 'off', 'Renderer', 'painters');
drawnow;
exportgraphics(fig, fullfile(outDir, [baseName, '.png']), 'Resolution', dpi, 'BackgroundColor', 'white');
end
