# Copyright (c) 2026 Islam Ibrahim. All rights reserved.





foundry_element="ge_pd_cml_oband_ushaped";
library_name="ge_pd_foundry";
jsonload(source_directory + '/ge_pd_cml_oband_ushaped.json');
feval(source_directory + '/QA/aux_scripts/photodetector_simple_backward.lsf');
process_prefix="ge_pd_";
model = process_prefix + 'ge_pd_cml_oband_ushaped';




design_kit_name = '::design kits::' + library_name + "::";
error_count = 0;
break_at_failure = false;
create_plots = true;

if(exist("container_selection_code")){
    foldername_ref = source_directory;
    filename_ref = child_model+"_refdata";
}else{
    foldername_ref = foundry_directory+"/source/"+foundry_element;
    filename_ref = foundry_element+"_refdata";
}

if(exist("stat_parameters")) {
    if(exist("container_selection_code")){
        filename_ref_stat = child_model+"_stat_refdata";
    }else{
        filename_ref_stat = foundry_element+"_stat_refdata";
    }
}

if(!exist("ele_an_2_RELAY")) {ele_an_2_RELAY = 0;}

if(!exist("opt_2_RELAY")) {opt_2_RELAY = 0;}

if(!exist("sample_rate_test")){
    sample_rate_test = 5e12;
}

if(!exist("DC_operation_only")){
    DC_operation_only =false;
}

if(!exist("stat_reference_data_available")){
    stat_reference_data_available = false;
}
if(!exist("enable_stat_qa")){
    enable_stat_qa = false;
}
if(!exist("bias_voltage_test")){
    bias_voltage_test = [-1];
}
if(!exist("wavelength_test")){
    wavelength_test = 1.55e-6;
}
if (exist("Resp_filename")) {Resp_data = readdata(source_directory+"/"+Resp_filename);}
if (exist("Idark_filename")) {Idark_data = readdata(source_directory+"/"+Idark_filename);}
if (exist("BW_filename")) {BW_data = readdata(source_directory+"/"+BW_filename);}



if(!exist("Idark_rel_tolerance")){
    Idark_rel_tolerance = 1e-2;
}

if(!exist("Iph_rel_tolerance")){
    Iph_rel_tolerance = 1e-2;
}

if(!exist("BW_rel_tolerance")){
    BW_rel_tolerance = 2e-2;
}

if(enable_stat_qa){
    if(!exist("N_trials")){
        N_trials = 50;
    }
    if(!exist("stat_qa_bias")){
        stat_qa_bias = 0;
    }    
    if(!exist('stat_Resp_tolerance')){
        stat_Resp_tolerance = 1e-3; 
    }
    
    if(!exist('stat_BW_tolerance')){
        stat_BW_tolerance = 0.01e9; 
    }
}
