# Copyright (c) 2026 Islam Ibrahim. All rights reserved.

script_dir  = filedirectory(which(currentscriptname));
device_dir  = script_dir + "/..";
project_dir = device_dir + "/projects";
repo_root   = device_dir + "/../..";
res_dir     = repo_root + "/results/device/doping/";

Npp_arr    = [5e19, 1e20, 5e20, 1e21];
nD         = length(Npp_arr);
V_ssac_arr = [-1.0];
nV_ssac    = length(V_ssac_arr);
V_start    = -2.5;
V_stop     =  0.0;
V_num      = 26;
# Save a private working copy once so the master .ldev is never modified by run()
tmp_file = project_dir + "/ge_pd_charge_doping_ushaped.ldev";
load(project_dir + "/ge_pd_charge_oband_ushaped.ldev");
switchtolayout;
save(tmp_file);

I_anode_dark_matrix = matrix(V_num, nD);
I_cathode_dark_matrix = matrix(V_num, nD);

for (iD = 1; iD <= nD; iD = iD + 1) {
    switchtolayout;
    select("CHARGE::Npp_contact");
    set("concentration", Npp_arr(iD));
    
    select("CHARGE::optical_gen");
    set("enabled", 0);
    select("CHARGE::boundary conditions::cathode");
    set("bc mode", "steady state");
    set("sweep type", "single");
    set("voltage", 0);
    set("apply ac small signal", "none");
    select("CHARGE::boundary conditions::anode");
    set("bc mode", "steady state");
    set("sweep type", "range");
    set("range start", 0.0);
    set("range stop",  -2.5);
    set("range num points", V_num);
    set("apply ac small signal", "none");
    select("CHARGE");
    set("solver mode", "steady state");
    run;
    
    anode_res = getresult("CHARGE", "anode");
    if (iD == 1) {
        V_arr_sweep = anode_res.V_anode;
    }
    I_anode_dark_matrix(1:V_num, iD) = anode_res.I;
    
    cathode_res = getresult("CHARGE", "cathode");
    I_cathode_dark_matrix(1:V_num, iD) = cathode_res.I;
}

V_sorted = matrix(V_num);
I_anode_dark_matrix_sorted = matrix(V_num, nD);
I_cathode_dark_matrix_sorted = matrix(V_num, nD);
for (iD = 1; iD <= nD; iD = iD + 1) {
    for (iV = 1; iV <= V_num; iV = iV + 1) {
        if (iD == 1) {
            V_sorted(iV) = V_arr_sweep(V_num - iV + 1);
        }
        I_anode_dark_matrix_sorted(iV, iD) = I_anode_dark_matrix(V_num - iV + 1, iD);
        I_cathode_dark_matrix_sorted(iV, iD) = I_cathode_dark_matrix(V_num - iV + 1, iD);
    }
}

doping_dark_I_anode = matrixdataset("I_anode");
doping_dark_I_anode.addparameter("V_anode", V_sorted);
doping_dark_I_anode.addparameter("Npp", Npp_arr);
doping_dark_I_anode.addattribute("I", I_anode_dark_matrix_sorted);

doping_dark_I_cathode = matrixdataset("I_cathode");
doping_dark_I_cathode.addparameter("V_anode", V_sorted);
doping_dark_I_cathode.addparameter("Npp", Npp_arr);
doping_dark_I_cathode.addattribute("I", I_cathode_dark_matrix_sorted);

matlabsave(res_dir + "ge_pd_charge_doping_dark_ushaped", doping_dark_I_anode, doping_dark_I_cathode, Npp_arr);


I_anode_illum_matrix = matrix(V_num, nD);
I_cathode_illum_matrix = matrix(V_num, nD);

for (iD = 1; iD <= nD; iD = iD + 1) {
    switchtolayout;
    select("CHARGE::Npp_contact");
    set("concentration", Npp_arr(iD));
    
    select("CHARGE::optical_gen");
    set("enabled", 1);
    select("CHARGE::boundary conditions::cathode");
    set("bc mode", "steady state");
    set("sweep type", "single");
    set("voltage", 0);
    set("apply ac small signal", "none");
    select("CHARGE::boundary conditions::anode");
    set("bc mode", "steady state");
    set("sweep type", "range");
    set("range start", 0.0);
    set("range stop",  -2.5);
    set("range num points", V_num);
    set("apply ac small signal", "none");
    select("CHARGE");
    set("solver mode", "steady state");
    run;
    
    anode_res = getresult("CHARGE", "anode");
    if (iD == 1) {
        V_arr_sweep = anode_res.V_anode;
    }
    I_anode_illum_matrix(1:V_num, iD) = anode_res.I;
    
    cathode_res = getresult("CHARGE", "cathode");
    I_cathode_illum_matrix(1:V_num, iD) = cathode_res.I;
}

V_sorted = matrix(V_num);
I_anode_illum_matrix_sorted = matrix(V_num, nD);
I_cathode_illum_matrix_sorted = matrix(V_num, nD);
for (iD = 1; iD <= nD; iD = iD + 1) {
    for (iV = 1; iV <= V_num; iV = iV + 1) {
        if (iD == 1) {
            V_sorted(iV) = V_arr_sweep(V_num - iV + 1);
        }
        I_anode_illum_matrix_sorted(iV, iD) = I_anode_illum_matrix(V_num - iV + 1, iD);
        I_cathode_illum_matrix_sorted(iV, iD) = I_cathode_illum_matrix(V_num - iV + 1, iD);
    }
}

doping_illum_I_anode = matrixdataset("I_anode");
doping_illum_I_anode.addparameter("V_anode", V_sorted);
doping_illum_I_anode.addparameter("Npp", Npp_arr);
doping_illum_I_anode.addattribute("I", I_anode_illum_matrix_sorted);

doping_illum_I_cathode = matrixdataset("I_cathode");
doping_illum_I_cathode.addparameter("V_anode", V_sorted);
doping_illum_I_cathode.addparameter("Npp", Npp_arr);
doping_illum_I_cathode.addattribute("I", I_cathode_illum_matrix_sorted);

matlabsave(res_dir + "ge_pd_charge_doping_illum_ushaped", doping_illum_I_anode, doping_illum_I_cathode, Npp_arr);

initialized_ssac = 0;
for (iD = 1; iD <= nD; iD = iD + 1) {
    for (iV = 1; iV <= nV_ssac; iV = iV + 1) {
        switchtolayout;
        select("CHARGE::Npp_contact");
        set("concentration", Npp_arr(iD));
        select("CHARGE::optical_gen");
        set("enabled", 1);
        select("CHARGE::boundary conditions::cathode");
        set("bc mode", "steady state");
        set("sweep type", "single");
        set("voltage", 0);
        set("apply ac small signal", "none");
        select("CHARGE::boundary conditions::anode");
        set("bc mode", "steady state");
        set("sweep type", "single");
        set("voltage", V_ssac_arr(iV));
        set("apply ac small signal", "none");
        select("CHARGE");
        set("solver mode", "ssac");
        set("small signal ac optical generation", true);
        set("frequency spacing", "log");
        set("log start frequency", 100e6);
        set("log stop frequency", 200e9);
        set("num frequency points per dec", 10);
        run;

        ssac_res = getresult("CHARGE", "ac_anode");
        if (initialized_ssac == 0) {
            f_arr = ssac_res.f;
            n_freq = length(f_arr);
            I_anode_ssac_matrix = matrix(n_freq, nD, nV_ssac);
            I_cathode_ssac_matrix = matrix(n_freq, nD, nV_ssac);
            initialized_ssac = 1;
        }
        I_anode_ssac_matrix(1:n_freq, iD, iV) = ssac_res.dI;
        ssac_res_cath = getresult("CHARGE", "ac_cathode");
        I_cathode_ssac_matrix(1:n_freq, iD, iV) = ssac_res_cath.dI;
    }
}

doping_ssac_I_anode = matrixdataset("I_anode");
doping_ssac_I_anode.addparameter("f", f_arr);
doping_ssac_I_anode.addparameter("Npp", Npp_arr);
doping_ssac_I_anode.addparameter("V_anode", V_ssac_arr);
doping_ssac_I_anode.addattribute("I", I_anode_ssac_matrix);

doping_ssac_I_cathode = matrixdataset("I_cathode");
doping_ssac_I_cathode.addparameter("f", f_arr);
doping_ssac_I_cathode.addparameter("Npp", Npp_arr);
doping_ssac_I_cathode.addparameter("V_anode", V_ssac_arr);
doping_ssac_I_cathode.addattribute("I", I_cathode_ssac_matrix);

matlabsave(res_dir + "ge_pd_charge_doping_ssac_ushaped", doping_ssac_I_anode, doping_ssac_I_cathode, Npp_arr, V_ssac_arr);
