function utils = thesis_utils()
% thesis_utils  Shared thesis figure styling and saving utilities
% Usage:
%   utils = thesis_utils();
%   style = utils.thesis_style(figure_dir);
%   utils.save_thesis_figure(fig_id, base_name, style);

utils.thesis_style       = @thesis_style;
utils.save_thesis_figure = @save_thesis_figure;
end

function style = thesis_style(figure_dir)
% thesis_style  Configure MATLAB defaults for publication-quality figures.
%   style = thesis_style(figure_dir)
style = struct( ...
    'figure_dir',  figure_dir, ...
    'font_size',   11, ...
    'font_name',   'Times New Roman', ...
    'line_width',  2, ...
    'grid_alpha',  0.15, ...
    'figure_pos',  [80, 80, 1600, 1000], ...
    'dpi',         300);
if ~exist(figure_dir, 'dir'), mkdir(figure_dir); end
set(groot, ...
    'defaultAxesFontSize',   style.font_size, ...
    'defaultAxesFontName',   style.font_name, ...
    'defaultLineLineWidth',  style.line_width, ...
    'defaultAxesBox',        'on', ...
    'defaultAxesLineWidth',  0.9, ...
    'defaultFigureColor',    'w');
end

function save_thesis_figure(fig_id, base_name, style)
% save_thesis_figure  Export figure as vector PDF + high-DPI PNG.
%   save_thesis_figure(fig_id, base_name, style)
fig = figure(fig_id);
set(fig, 'Color', 'w', 'InvertHardcopy', 'off', ...
    'Renderer', 'painters', 'Position', style.figure_pos);
axes_list = findall(fig, 'Type', 'axes');
for k = 1:numel(axes_list)
    set(axes_list(k), ...
        'FontName',       style.font_name, ...
        'FontSize',       style.font_size, ...
        'LineWidth',      1.2, ...
        'GridAlpha',      style.grid_alpha, ...
        'MinorGridAlpha', 0.08, ...
        'TickDir',        'out');
end
drawnow;
exportgraphics(fig, fullfile(style.figure_dir, [base_name, '.pdf']), ...
    'ContentType', 'vector', 'BackgroundColor', 'white');
exportgraphics(fig, fullfile(style.figure_dir, [base_name, '.png']), ...
    'Resolution', style.dpi, 'BackgroundColor', 'white');
fprintf('Saved %s.[pdf|png]\n', fullfile(style.figure_dir, base_name));
end
