# Copyright (c) 2026 Islam Ibrahim. All rights reserved.

err = 0;
error_count = 0;

design_kit_name = "::design kits::" + library_name + "::";

new;
groupscope("::Root Element");
set("sample rate", 1e12);
set("number of samples", 2048);

addelement(design_kit_name + model);
DUT_name = get("name");
set("x position", 0);
set("y position", 0);

addelement("CW Laser");
CWL_name = get("name");
set("frequency", 229007633587786.28);
set("power", 1e-4);
set("x position", -250);
set("y position", 0);

addelement("Oscilloscope");
OSC_name = get("name");
set("x position", 250);
set("y position", 0);

connect(CWL_name, "output", DUT_name, "input");
connect(DUT_name, "output", OSC_name, "input");

run;

msg = "ge_pd_cml_oband_ushaped exposes standard input/output ports and runs.";
assert(msg, true);
